### ISSUE TITLE
Safari: no tasks error

### ISSUE THREAD

**Issue by ifilipis** [Tascana/tascana-web#10]
<img width="1029" alt="Снимок экрана 2020-01-17 в 0 56 49" src="https://user-images.githubusercontent.com/40601736/72558315-3f99a200-38c4-11ea-82af-abb6446522e7.png">

**Comment by shashkovdanil** [comment]
Сделано здесь: https://github.com/Tascana/tascana-web/commit/93c4a3001dbf7466d7ece19a6c9906cf09988926
