### ISSUE TITLE
Отображать название каждого месяца целиком

### ISSUE THREAD

**Issue by ifilipis** [Tascana/tascana-web#15]
![image](https://user-images.githubusercontent.com/40601736/72662955-d5d9df00-3a0e-11ea-94bb-3dd68fdc7a08.png)
![image](https://user-images.githubusercontent.com/40601736/72662957-d96d6600-3a0e-11ea-8b8b-5ba945f9cc69.png)

Оставить today, tomorrow, yesterday, this month, next month и previous month

**Comment by shashkovdanil** [comment]
Сделано здесь https://github.com/Tascana/tascana-web/commit/94fb7d99f2199b8168acd2c1dea4d3c5d8076e96
