### ISSUE TITLE
Progress bar not updating

### ISSUE THREAD

**Issue by ifilipis** [Tascana/tascana-web#18]
<img width="444" alt="Снимок экрана 2020-01-23 в 0 58 48" src="https://user-images.githubusercontent.com/40601736/72938185-8df2e900-3d7b-11ea-9b52-2217b1aee64c.png">
Add new task -> Mark done -> Add another task
Give estimate should be 50%

**Comment by ifilipis** [comment]
<img width="647" alt="Снимок экрана 2020-01-26 в 13 46 56" src="https://user-images.githubusercontent.com/40601736/73134020-536ea200-4042-11ea-8b1b-ec1d062fc7b2.png">

**Comment by ifilipis** [comment]
[Запись экрана 2020-02-23 в 16.54.50.zip](https://github.com/Tascana/tascana-web/files/4241328/2020-02-23.16.54.50.zip)

**Comment by shashkovdanil** [comment]
А почему здесь дневные таски имеют ооочень старый дизайн? Этто видимо на какой-то старой ветке такой баг был?

**Comment by ifilipis** [comment]
Видео от 23 февраля. Тогда еще было актуально

**Comment by shashkovdanil** [comment]
А сейчас актуально? Я не смог воспроизвести, видео прилагаю

[2020-02-29 12-18-14.zip](https://github.com/Tascana/tascana-web/files/4270024/2020-02-29.12-18-14.zip)
