### ISSUE TITLE
Рефакторинг функционала свайпов

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#22]
*Понятия:*

Лайн - горизонтальный блок, который мы свайпаем. Всего на странице их 3: годовой, месячный и дневной.

*Проблема:*

Текущий код очень тяжелый для восприятия: сложная логика обновления дат в Redux mapStateToProps, таймауты внутри таймаутов, несколько `useEffect` и т.д. и т.п.

*Требования:*

- По свайпу мы должны пролистывать год, месяц, день (в зависимости от свайпнутого лайна)
- Даты должны свайпаться корректно (свайпнули с декабря на январь, должен свайпнуться год на +1)
- В лайнах должны отображаться актуальные таски для той даты, которая сейчас видима на странице
- Нужно написать комменты в коде к функционалу свайпов (это нужно для меня, как я все пойму, можно будет их выпилить)
- По клику на края экрана должен срабатывать свайп
- Нужно учесть, что по клику на таск у нас сработает выбор этого таска, то есть нужно сделать так, чтобы при свайпе выбор не сработал
- После обсуждений было принято решение, что нам не нужны свайпы влево/вправо до бесконечности. Работаем в пределе 11 лет (если сейчас 2020, то мы должны иметь диапазон от 2019-2030, то есть прошлый год сохраняем, для людей, которые захотят зафиксировать прошлогодние задачи)

*Сейчас:*

Сейчас это реализовано следующим образом (описан будет только годовой лайн, для месячного и дневного функционал аналогичный):

1. На странице в одном лайне хранится 3 даты, они выбираются по следующему принципу: если выбранный год 2020, то в лайне будет 2019, 2020, 2021
2. После свайпа на 2021 лайн обновится следующим образом 2020, 2021, 2022
3. Анимации и свайпы работают с использованием либ: react-spring + react-use-gesture
4. Данные лайна хранятся в Redux Store, в объекте UI

И так до бесконечности. Можно пролистать хоть до 10000+ года.

Код компонента: https://github.com/Tascana/tascana-web/blob/develop/src/components/Lines/index.js

**Comment by pavelk2** [comment]
**про комменты** - пожалуйста не нужно их выпиливать, и желательно писать их к большему количеству компонентов и желательно писать их на английском языке (думаю в будущем с нами будут работать не только русско-говорящие ребята).

**браузеры** - по умолчанию давайте тестировать каждую фичу как минимум в последних Safari, Chrome, Firefox. Далее будем разбираться как тестировать в более старых браузерах и какие поддерживать, какие нет.

**Comment by ifilipis** [comment]
Еще надо не забыть, что если текущая дата 31 января, то при скролле месяца на февраль, дата становится 28/29 февраля. То же самое в обратную сторону: 31 мая -> 30 апреля

При свайпе меняется высота блока задач по прилетающему новому блоку, в зависимости от направления свайпа. Насколько я помню, берется максимальная высота от двух. То же происходит для зависимых строк.

При обновлении зависимых строк, происходит следующее (на примере месячной):
Например, перелистывается год 2019->2020. 
Текущий месяц: февраль 2019.
Загруженные данные в месячном блоке [январь 2019],[фераль 2019],[март 2019]
1. В зависимости от направления движения загружается новый блок, загруженные данные становятся такими
[февраль 2019],[февраль 2020],[март 2020]
2. Без анимации производится смещение блоков так, чтобы текущий месяц остался на месте
3. Анимируется переход со старого месяца на новый + анимируется высота блока
4. Загружаются последовательные месяцы
[январь 2020],[февраль 2020],[март 2020]

Поскольку анимации частично привязаны к useState, это помогает также менять высоту блока с анимацией при добавлении задач. 

Обратите внимание на резкие свайпы. Поскольку react-use-gesture отрабатывает не каждый кадр, могут возникнуть заметные скачки при перемещении блоков. В текущей версии реализована компенсация положения курсора, которая их полностью убирает

**Comment by julie-volkova** [comment]
Я порефакторил компонент и немного поделил его на отдельные модули. 

Появилась еще идея, на нее на этих выходных пока не хватило времени. В редакс сторе очень много манипуляций с датами, мне кажется это не нужно. Можно заменить одной строкой времени в формате ISO и манипулировать ей с помощью date-fns. Могу попозже этим заняться.

**Comment by julie-volkova** [comment]
`По клику на края экрана должен срабатывать свайп
 `

Так же реализовано

**Comment by ifilipis** [comment]
Closed?
