### ISSUE TITLE
Allow to undone monthly tasks (show the checkbox checked on hover)

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#29]
Имеется выполненный месячный таск. Сейчас у нас нет быстрого способа вернуть его в невыполненное состояние.

*Требования:*

- Нужно сделать, чтобы на hover появлялась иконка чекбокса, по нажатию на которую таск становился невыполненным.
- Нужно заменить текст в context menu с `Done` на `Undone`, если задача выполнена

*Вопросы:*

1. Нужен макет таска с состоянием `Done hover` вот здесь: https://zpl.io/VxXBqq3

**Comment by ifilipis** [comment]
Обновил zeplin
