### ISSUE TITLE
Add a button to yearly task: flip a color - you click and another random color is applied, otherwise some colors are quite bad :)

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#30]
*Требования:*

- В годовой таск добавить кнопку для смены цвета
- По нажатию на эту кнопку меняется цвет у всех дочерних задач

*Вопросы:*

- Нужен дизайн этой кнопки вот здесь https://zpl.io/VxXBqq3
- По какому принципу должен работать рандом? Сейчас градиент считается по функции `randomGrad(lastTaskIndex + 1)`, то есть он завязан на индексе таска внутри массива.
- Можем ли мы у одного таска бесконечно менять цвета?

**Comment by ifilipis** [comment]
Откуда эта задача?

**Comment by shashkovdanil** [comment]
![Аннотация 2020-02-21 133548](https://user-images.githubusercontent.com/19692986/75017583-1f569780-54af-11ea-84c9-d59068c299ac.png)

Из `Project -> MVP -> To do next week`

**Comment by ifilipis** [comment]
В меню по правому клику добавить "Change color"

**Comment by ifilipis** [comment]
<img width="1023" alt="Снимок экрана 2020-03-01 в 23 01 20" src="https://user-images.githubusercontent.com/40601736/75632761-92c77a00-5c10-11ea-9712-d9757a877741.png">
Change color на месячной задаче
