### ISSUE TITLE
Task parent manual assignment (make it work on color select) Blur is not intuitive.

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#32]
*Требования:*

- При линковании месячной задачи, выбор родительской должен срабатывать на single click, а не на blur

*Вопросы:*

1. Правильно ли я понял задачу?

**Comment by ifilipis** [comment]
Сейчас, вроде, правильно реализовано

**Comment by shashkovdanil** [comment]
> Сейчас, вроде, правильно реализовано

Сейчас по клику мы просто видим как меняется цвет у задачи, но если мы например перезагрузим в этом момент страницу, то линк не сохранится и задача останется не приявязанной, потому что линк задачи происходит именно на `blur`, а в задаче указано, что `Blur is not intuitive`

**Comment by ifilipis** [comment]
Обсудим на звонке

**Comment by ifilipis** [comment]
Можно сделать так: highlight на single click, сохранение на double click. Но без задержки в N мс после клика. Я уже писал где-то, как это сделать
Но onBlur оставить
