### ISSUE TITLE
Error while deleting yearly task - check the screenshot

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#33]
*Ожидание:*

- При удалении годовой задачи не возникнет ошибки

*Реальность:*

Сейчас ошибка есть.

*Вопросы:*

1. После удаления родительской задачи дочерние должны удалиться или стать unassigned?

**Comment by ifilipis** [comment]
Нужно пофиксить баг с данными. Предварительно, удаляются и дочерние, и сама задача. Но должен остаться режим (в коде), когда дочерние остаются

**Comment by shashkovdanil** [comment]
О каком баге с данными идет речь?

**Comment by ifilipis** [comment]
У меня возникала ошибка при удалении годовой задачи. Если сейчас нет, то ок
