### ISSUE TITLE
Change Website title to Tascana, and logo to the circle with gradient

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#34]
*Требования:*

- Сменить title страницы на `Tascana`
- Добавить фавиконку

*Вопросы:*

1. Нужен `*.png` файл с фавиконкой
2. Заголовок `Tascana` будет у всех страниц? Или на лэндинге он мб какой-нибудь другой будет?

**Comment by ifilipis** [comment]
Нужно еще обновить все meta теги. Напишу позже все поля

**Comment by shashkovdanil** [comment]
Нужна иконка размером 32х32

**Comment by ifilipis** [comment]
```
<meta property="og:title" content="Tascana">
<meta property="og:description" content="Achieve your long-term goals with Tascana">
<meta property="og:image" content="вставить url картинки">
<meta property="og:url" content="https://www.tascana.com/">
<meta property="og:site_name" content="Tascana">
<meta property="og:type" content="website">
<meta name="description" content="Achieve your long-term goals with Tascana">
```
![header-graphics](https://user-images.githubusercontent.com/40601736/75625607-ce425400-5bd0-11ea-995a-51a899d1b557.jpg)
