### ISSUE TITLE
Remove all text in a task - confirmation if one wants to delete the task "yes/no" (simply alert with confirmation). Do not show the confirmation for daily task -> delete on blur

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#38]
*Требования:*

- Если мы, редактируя задачу удаляем из нее все символы, то мы должны увидеть диалоговое окно с вопросом типа "Хотите ли вы удалить задачу? Да/Нет". Актуально только для месячных и годовых задач.

- Если мы, редактируя ДНЕВНУЮ задачу удаляем из нее все символы и кликаем вне ее (событие blur), то задача должна удалиться без диалогового окна.

*Вопросы:*

1. Правильно ли я понял задачу?
2. Что должно произойти если мы не хотим удалять задачу (кнопка "Нет" в диалоговом окне)? Вернуть тот текст, который в ней был изначально?
3. Какой дизайн будет у диалогово окна?
4. Диалоговое окно должно появиться на событие `blur` или как только мы удалим все символы?

**Comment by ifilipis** [comment]
2. Да, вернуть текст
3. alert() возможно, вроде?
4. На blur

У таск бокса есть событие onBlur, в него надо добавить проверку количества символов. Если 0, то делать все вышеописанное
