### ISSUE TITLE
Burger menu next to "Checkbox". On burger menu click we get a popup window with Edit/Delete/Done

### ISSUE THREAD

**Issue by shashkovdanil** [Tascana/tascana-web#40]
*Требования:*

- Сделать аналог контекстного меню для мобильной версии

*Вопросы:*

1. Какой дизайн будет у попапа с кнопками `Edit/Done/Delete`.
2. Как будет выглядеть иконка `Burger menu` в таскбоксе

**Comment by ifilipis** [comment]
Только для мобильных браузеров

**Comment by ifilipis** [comment]
Обновил zeplin

**Comment by ifilipis** [comment]
<img width="715" alt="Снимок экрана 2020-02-24 в 16 17 06" src="https://user-images.githubusercontent.com/40601736/75155444-1c62dd80-5721-11ea-816b-2e1bdbb38957.png">
Always = всегда видно

**Comment by ifilipis** [comment]
<img width="185" alt="Снимок экрана 2020-02-28 в 21 47 55" src="https://user-images.githubusercontent.com/40601736/75578088-45aea100-5a74-11ea-913b-2996e52ef6d8.png">
Иконка не встает в угол сама

**Comment by ifilipis** [comment]
И думаю, что порядок должен быть такой:
Done, link и more

**Comment by ifilipis** [comment]
Burger menu не должно быть на десктопе
Ну и порядок иконок Done, link и more

**Comment by ifilipis** [comment]
<img width="219" alt="Снимок экрана 2020-02-29 в 14 54 58" src="https://user-images.githubusercontent.com/40601736/75606966-78ec4100-5b03-11ea-8ef0-1dee99ece50c.png">
Добавлю сюда баг. Кружки теперь показываются слева

**Comment by ifilipis** [comment]
Оу, только что заметил, что на годовой задаче все еще большие иконки в десктопе
