### ISSUE TITLE
UI Bugs list

### ISSUE THREAD

**Issue by ifilipis** [Tascana/tascana-web#41]
- [x] Progress bar - вернуть старый SVG модуль. Новый не соответствует дизайну
- [x] Сколл стрелками происходит без анимации
- [x] Скролл при нажатии на край экрана происходит без анимации в дневном блоке
- [x] Скролл стрелками происходит при редактировании задач [Screen Recording 2020-02-18 at 19.52.24.mp4.zip](https://github.com/Tascana/tascana-web/files/4239375/Screen.Recording.2020-02-18.at.19.52.24.mp4.zip)
- [x] Анимация при смене дат работает неправильно. Меняется день вперед - прилетает день справа. Меняется месяц назад - прилетают месяц и день слева.
- [x] Плашка на hover у свернутой задачи должна быть смещена влево
- [x] Datepicker в header должен следовать этой логике https://gist.github.com/ifilipis/e8eef4cf69e19c7247480d3fc581cffa
- [x] При свернутом блоке задач, два соседних остаются развернутыми, анимация работает неправильно[Запись экрана 2020-02-16 в 12.20.19.mov.zip](https://github.com/Tascana/tascana-web/files/4239377/2020-02-16.12.20.19.mov.zip)
- [x] Скролл на мобильной версии работает очень плохо (iOS 12, 13, Safari) [IMG_8248.mp4.zip](https://github.com/Tascana/tascana-web/files/4239373/IMG_8248.mp4.zip)
- [x] Кружок в дневном блоке съезжает вниз при редактировании/добавлении [Запись экрана 2020-02-22 в 16.02.28.zip](https://github.com/Tascana/tascana-web/files/4239380/2020-02-22.16.02.28.zip)
- [x] Drag'n'drop bugs - ломаются стили [Screen Recording 2020-02-17 at 21.25.26.mp4.zip](https://github.com/Tascana/tascana-web/files/4239382/Screen.Recording.2020-02-17.at.21.25.26.mp4.zip)
- [x] У заголовков блоков задач появился класс. Стиль должен соответствовать стилю h1. Стили заголовков месячных, дневных, годовых задач разные.
- [x] Когда завожу месячные задачи они дробятся на 2 строки, когда сохраняю - показываются в одну строку
- [x] Задержка при выделении задач. Сейчас click обрабатывается через N мс после нажатия. Надо: обрабатывать click сразу, обрабатывать double-click, если click случился за N мс до события.
- [x] Scroll bug неизвестного происхождения [Запись экрана 2020-02-22 в 15.53.21.zip](https://github.com/Tascana/tascana-web/files/4239369/2020-02-22.15.53.21.zip)
- [x] При редактировании месяца стиль задачи меняется на done

**Comment by ifilipis** [comment]
- [x] Кружок в дневном блоке все еще съезжает вниз при редактировании/добавлении

[Запись экрана 2020-02-23 в 15.44.20.zip](https://github.com/Tascana/tascana-web/files/4241245/2020-02-23.15.44.20.zip)

**Comment by ifilipis** [comment]
- [x] Еще текст в месячном блоке скачет в режиме редактирования 
[Запись экрана 2020-02-23 в 17.29.15.zip](https://github.com/Tascana/tascana-web/files/4241407/2020-02-23.17.29.15.zip)

**Comment by ifilipis** [comment]
- [x] Меняется размер иконки при клике [Запись экрана 2020-02-26 в 20.45.18.zip](https://github.com/Tascana/tascana-web/files/4257321/2020-02-26.20.45.18.zip)

**Comment by shashkovdanil** [comment]
> Задержка при выделении задач. Сейчас click обрабатывается через N мс после нажатия. Надо: обрабатывать click сразу, обрабатывать double-click, если click случился за N мс до события.

Не понимаю как это в принципе должно работать. Если клик будет вообще без задержки, то у нас тогда мгновенно на нажатие сработает выделение дерева тасков (если вести речь о клике на таск), то есть нажав дважды у нас произойдет следующее:

Первый клик -> выделенеие дерева тасков -> второй клик -> режим редактирования.

И по итогу мы получим два варианта либо мигание выделения дерева тасков, либо вход выделение дерева тасков + режим редактирования

**Comment by ifilipis** [comment]
Так и должно быть. Выделение дерева тасков + режим редактирования

https://github.com/Tascana/tascana-web/blob/0a0a91899be23536b3e90fbc19b71a8f5840590d/src/components/task-box.js#L74

**Comment by shashkovdanil** [comment]
> Progress bar - вернуть старый SVG модуль. Новый не соответствует дизайну

А в чем конкретно не соответствует дизайну? Там разница в высоте была на 1px, я это поправил, больше разницы не вижу

**Comment by ifilipis** [comment]
<img width="401" alt="Снимок экрана 2020-02-29 в 14 46 33" src="https://user-images.githubusercontent.com/40601736/75606868-49890480-5b02-11ea-96b8-0f1df5798ebe.png">

**Comment by shashkovdanil** [comment]
Я разницы не вижу. Желательно пример сайта и пример с макета с указанием разницы. А вообще я выпилил свгшку, потому что с ней было 2 проблемы:

1. Высота всей свг была 200px, что вызывало баги в месячных тасках, т.к. их высота 100px
2. В годовом таске у нас прогресс бар белый, а в месячных градиентный, поэтому одну и ту же свг использовать не получилось бы

**Comment by ifilipis** [comment]
<img width="401" alt="75606868-49890480-5b02-11ea-96b8-0f1df5798ebe" src="https://user-images.githubusercontent.com/40601736/75625465-63dce400-5bcf-11ea-8a2b-3bee565d0b01.png">

**Comment by ifilipis** [comment]
У SVG меняется высота, offset и все остальное
