### ISSUE TITLE
Progress bar calculation

### ISSUE THREAD

**Issue by ifilipis** [Tascana/tascana-web#42]
1. Взять id из годовой задачи. Создать переменные total и done.
2. Получить все задачи, у которых parentid равен id.
3. Каждой из задач взять children.length. 
4. Если children.length > 0, то считать сложить количество выполненных задач из children. Прибавить children.length в total, children -> done в done.
5. Если == 0, смотреть, выполнена, или нет, сама задача. Добавить 1 в total и done в done.
6. Разделить done на total

**Comment by julie-volkova** [comment]
Мне кажется что сейчас progress bar вычисляется так, как мы обсуждали, поправьте если не прав
