### ISSUE TITLE
Yearly goal lost its color

### ISSUE THREAD

**Issue by pavelk2** [Tascana/tascana-web#48]
When a monthly task was deleted the associated yearly task became grey.

Expectation: the deletion of a monthly task should not affect the yearly parent goal in any way.
![Screenshot 2020-02-22 at 20 46 02](https://user-images.githubusercontent.com/1285967/75098292-87db6c80-55b4-11ea-8a00-f4de63c87390.png)

**Comment by shashkovdanil** [comment]
@pavelk2 , cannot reproduce

**Comment by shashkovdanil** [comment]
[2020-02-23 13-02-25.zip](https://github.com/Tascana/tascana-web/files/4240696/2020-02-23.13-02-25.zip)

**Comment by shashkovdanil** [comment]
Need more info for reproduce
