### ISSUE TITLE
Selection tree not working on year tasks

### ISSUE THREAD

**Issue by ifilipis** [Tascana/tascana-web#53]
Child tasks are not selected
<img width="1680" alt="Снимок экрана 2020-02-23 в 15 48 37" src="https://user-images.githubusercontent.com/40601736/75112350-076c4880-5654-11ea-8d97-422274830258.png">

**Comment by shashkovdanil** [comment]
Cannot reproduced

![Uploading Аннотация 2020-02-28 221508.png…]()

**Comment by shashkovdanil** [comment]
Can't reproduce

![ads](https://user-images.githubusercontent.com/19692986/75569947-e81c5380-5a77-11ea-98f8-29eb247d4894.png)

**Comment by ifilipis** [comment]
Will reopen if repeats
