### ISSUE TITLE
Scroll bugs

### ISSUE THREAD

**Issue by pavelk2** [Tascana/tascana-web#6]
Phillip has a .mov file in Telegram channel

**Comment by ifilipis** [comment]
[Запись экрана 2020-01-17 в 1.33.55.zip](https://github.com/Tascana/tascana-web/files/4073685/2020-01-17.1.33.55.zip)
Проблема в том, что следующий/предыдущий год перемещается, кажется, не в ту сторону. immediate: true было как раз для того, чтобы компенсировать смещение в массиве items [2019],[2020],[2021] -> [2018],[2019],[2020] например

**Comment by ifilipis** [comment]
В issue #2 описывается процесс скролла

**Comment by ifilipis** [comment]
[Запись экрана 2020-01-18 в 16.27.58.zip](https://github.com/Tascana/tascana-web/files/4080505/2020-01-18.16.27.58.zip)
Дни не скроллятся

**Comment by ifilipis** [comment]
Animation bug - done
Data bug - done
