### ISSUE TITLE
 Double tap to edit make sure it works

### ISSUE THREAD

**Issue by julie-volkova** [Tascana/tascana-web#60]
/\

**Comment by julie-volkova** [comment]
can't reproduce :(

**Comment by ifilipis** [comment]
On mobile

**Comment by julie-volkova** [comment]
> On mobile

works fine for me
could you provide a video?

**Comment by ifilipis** [comment]
[RPReplay_Final1582659169.MP4.zip](https://github.com/Tascana/tascana-web/files/4251801/RPReplay_Final1582659169.MP4.zip)
2/5
