### ISSUE TITLE
Safari: Select after drag

### ISSUE THREAD

**Issue by pavelk2** [Tascana/tascana-web#7]

**Comment by ifilipis** [comment]
Tile selection issue is now fixed, but page flip causes content selection

**Comment by ifilipis** [comment]
Possible solution https://stackoverflow.com/questions/6562727/is-there-a-function-to-deselect-all-text-using-javascript

**Comment by ifilipis** [comment]
[Запись экрана 2020-02-24 в 16.00.45.zip](https://github.com/Tascana/tascana-web/files/4244801/2020-02-24.16.00.45.zip)

**Comment by ifilipis** [comment]
[Запись экрана 2020-03-01 в 4.12.33.zip](https://github.com/Tascana/tascana-web/files/4271189/2020-03-01.4.12.33.zip)
Не пофикшено

**Comment by shashkovdanil** [comment]
Fixed
