### ISSUE TITLE
Task linking - hover works incorrectly

### ISSUE THREAD

**Issue by ifilipis** [Tascana/tascana-web#73]
<img width="666" alt="Снимок экрана 2020-02-26 в 22 52 34" src="https://user-images.githubusercontent.com/40601736/75381933-af9b3f00-58ea-11ea-9daf-2ef448e7be43.png">

**Hover** on circle will highlight new parent

**Single click** will highlight new parent **and** paint border from grey -> parent color

FYI

**Blur** will save new parent

**Comment by ifilipis** [comment]
<img width="207" alt="Снимок экрана 2020-02-29 в 15 00 12" src="https://user-images.githubusercontent.com/40601736/75607047-324b1680-5b04-11ea-948c-3e1ac9cbeb2a.png">
Кружки показываются слева, hover еще не пофикшен

**Comment by shashkovdanil** [comment]
> Кружки показываются слева, hover еще не пофикшен

Fixed

**Comment by julie-volkova** [comment]
that was probably fixed

**Comment by ifilipis** [comment]
Не, надо сделать подсвечивание задач по ховеру, а не по клику. Сейчас по клику

**Comment by julie-volkova** [comment]
> Не, надо сделать подсвечивание задач по ховеру, а не по клику. Сейчас по клику

Точно уверен? На мобилках нет ховера ведь

**Comment by ifilipis** [comment]
На мобилках ховер по тапу срабатывает

**Comment by julie-volkova** [comment]
> На мобилках ховер по тапу срабатывает

Понимаю, сделаем.
