### ISSUE TITLE
Move React app to production

### ISSUE THREAD

**Issue by pavelk2** [Tascana/tascana-web#82]
Currently sometimes the app crashes, and users abandon the web service. It would be great if the app does not crash, and if there is some error - we should have a way to log this error, for example using Heroku.

**Comment by julie-volkova** [comment]
deployed the latest version to tascana.com

https://www.tascana.com/

**Comment by ifilipis** [comment]
Была такая штука, что tascana.com деплоилась в debug mode. Не знаю, пофикшено или нет
